fryCaptain/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resturant.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

resturant/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'), #home page
    path('menu/', views.menu, name='menu'), #menu page
    path('menu/<str:pk>/details', views.menu_details, name="menu_details"),

    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutPage, name="logout"),
    path('profile/', views.userProfile, name="user_profile"),

    path('menu_adjustment/', views.adminMenuItem, name="admin_menu_item"),
    path('menu_adjustment/order/<str:pk>', views.orderDetails, name="order_details"),
    path('<str:pk>/details/delete/', views.delete_item, name="delete_item"),
    path('profile/password_change/', views.passwordChange, name='password_change'),
    path('<str:pk>/details/', views.adminMenuItemDetails, name='admin_detail'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="resturant/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="resturant/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="resturant/password_reset_form.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="resturant/password_reset_done.html"),
         name="password_reset_complete"),

    path('cart/', views.cartView, name='cart'),
    path('cart/checkout/', views.checkoutView, name='checkout'),
    path('menu/update_item/', views.updateItem, name="update_item"),
    path('cart/update_item/', views.updateItem, name="update_item"),
    path('cart/checkout/update_delivery_info/', views.updateDeliveryInfo, name='update_delivery_info'),
    path('cart/checkout/process_order/', views.processOrder, name='process_order'),
    path('order_items_count/', views.orderCount, name='order_count'),
]

resturant/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.forms import CheckboxSelectMultiple
# Create your models here.

class MyModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.ManyToManyField: {'widget': CheckboxSelectMultiple},
    }

class MenuItem(models.Model):
    ITEMTYPE = (
                ('fries','fries'),
                ('entree', 'entree'),
                ('dessert', 'dessert'),
                ('sauce', 'sauce'),
                )
    SAUCETYPE = (
            ('aioli','aioli'),
            ('ketchup', 'ketchup'),
    )
    name = models.CharField(max_length = 50, null=True)
    sauce_type = models.CharField(max_length=200, null=True, blank=True, choices=SAUCETYPE)
    description = models.TextField(max_length = 250, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    item_type = models.CharField(max_length=200, null=True, choices=ITEMTYPE)
    date_created = models.DateTimeField(auto_now_add = True, null=True)
    item_pic = models.ImageField(default='solid-dark-grey-background.jpg',null=True, blank=True)

    def __str__(self):
        return self.name;

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length = 50, null=True)
    email = models.CharField(max_length = 100, null=True)
    phone = models.CharField(max_length = 15, null=True)
    profile_pic = models.ImageField(default='defaultProfilePic.png',null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add = True, null=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    STATUS = (
            ('Order In Progress', 'Order In Progress'),
            ('Order Confirmed', 'Order Confirmed'),
            ('Out for delivery', 'Out for delivery'),
            ('Arrived', 'Arrived'),
            )

    pickup = models.BooleanField(default=False, null=True)
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add = True, null=True)
    status = models.CharField(max_length=200, null=True, choices = STATUS)
    transaction_id = models.CharField(max_length=200, null=True)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    def __str__(self):
        return self.customer.name + "'s order with id: " + str(self.id)

class OrderItem(models.Model):
    product = models.ForeignKey(MenuItem, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.OneToOneField(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

resturant/forms.py
from django.forms import ModelForm, FileInput
from .models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import CheckboxSelectMultiple

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        exclude=['pickup', 'customer', 'transaction_id']

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'groups']

class UpdateUserProfile(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class CustomerSettingUpdateForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']
        widgets={
            'profile_pic': FileInput()
        }

class AddMenuItem(ModelForm):
    class Meta:
        model = MenuItem
        fields ="__all__"
        widgets={
            'item_pic': FileInput()
        }

resturant/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import *
from .forms import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from .decorators import *
from django.contrib.auth.models import User, Group
from django.urls import reverse_lazy
import json, datetime
from .utils import *
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def orderCount(request):
    data = json.loads(request.body)

    if request.user.is_authenticated:
        order = request.user.customer.order_set.get(status="Order In Progress")
        itemCount = {"item_count": order.get_cart_items}
    else:
        cookieTotal = 0

        for i in data:
            cookieTotal += int(data[str(i)]['quantity'])

        itemCount={'item_count' : cookieTotal}

    return JsonResponse(itemCount)


def orderDetails(request, pk):
    currentOrder = Order.objects.get(id=pk)
    orderItems = currentOrder.orderitem_set.all()

    try:
        shippingAddress = currentOrder.customer.shippingaddress
    except:
        shippingAddress = "Customer has no shipping address"

    form = OrderForm(instance=currentOrder)

    if request.method == "POST":
        form = OrderForm(request.POST, instance=currentOrder)
        if form.is_valid():
            form.save()
            return redirect("admin_menu_item")

    context = {
     "form" : form,
     "order" : currentOrder,
     "order_items" : orderItems,
     "shipping_address" : shippingAddress,
    }
    return render(request, 'resturant/order_details.html', context)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp();
    data = json.loads(request.body)

    print(data)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, status="Order In Progress")
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.status = "Order Confirmed"
    order.save()

    if order.pickup == False:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse("Hello", safe=False)

def updateDeliveryInfo(request):
    data = json.loads(request.body)

    checkValue = data['buttonChecked']
    orderId = data['orderId']

    if(orderId):
        currentOrder = Order.objects.get(id=orderId)

        if(checkValue=="pickup"):
            currentOrder.pickup = True
        else:
            currentOrder.pickup = False

        currentOrder.save()

    return JsonResponse("Request Successful", safe=False);

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    customer = request.user.customer
    product = MenuItem.objects.get(id=productId)

    order, created = Order.objects.get_or_create(customer=customer, status="Order In Progress")
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == "add":
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == "remove":
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False);

def checkoutView(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {
        'items' : items,
        'order' : order,
        'cart-items': cartItems,
    }
    return render(request, 'resturant/checkout.html', context)

def cartView(request):
    try:
        data = cartData(request)
        cartItems = data['cartItems']
        order = data['order']
        items = data['items']
    except:
        pass
    context = {
        'items' : items,
        'order' : order,
        'cart-items' : cartItems,
    }
    return render(request, 'resturant/cart.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def adminMenuItemDetails(request, pk):
    currentItem = MenuItem.objects.get(id=pk)
    form = AddMenuItem(instance=currentItem)
    if request.method == 'POST':
        form = AddMenuItem(request.POST, request.FILES, instance=currentItem)
        if form.is_valid():
            user = form.save()
            return redirect('admin_menu_item')
        else:
            print(form.errors)

    context = {
        'form': form,
        'item': currentItem,
    }
    return render(request, 'resturant/menu_items_details_admin.html', context)


@login_required(login_url='login')
def passwordChange(request):
    errorList=[]
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')

            return redirect('user_profile')
        else:
            print(form.errors)
            for key, value in form.errors.items():
                errorList.append(value)
    else:
        form = PasswordChangeForm(user=request.user)

    context = {
        'form' : form,
        'errors' : errorList,
    }

    return render(request, 'resturant/password_change.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def delete_item(request, pk):
    seletedItem = MenuItem.objects.get(id=pk)

    if request.method == "POST":
        seletedItem.delete()
        return redirect('admin_menu_item')

    context = {
        'item': seletedItem,
    }

    return render(request, 'resturant/delete_item.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['customer'])
def userProfile(request):
    currentUser = request.user.customer
    form = CustomerSettingUpdateForm(instance=currentUser)
    if request.method == "POST":
        form = CustomerSettingUpdateForm(request.POST, request.FILES, instance=currentUser)
        if form.is_valid():
            form.save()


    context = {
        'current_user' : currentUser,
        'form' : form,
    }
    return render(request, 'resturant/user_profile.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def adminMenuItem(request):
    #form handling
    items = MenuItem.objects.all()
    form = AddMenuItem()
    confirmedOrders = Order.objects.filter(status="Order Confirmed")
    beingDeliveredOrders = Order.objects.filter(status="Out for delivery")


    if request.method =="POST":
        form = AddMenuItem(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('admin_menu_item')

    context = {
        'items': items,
        'form': form,
        'confirmed_orders': confirmedOrders,
        'orders_being_delivered' : beingDeliveredOrders,
    }
    return render(request, 'resturant/admin_menu_item.html', context)


def home(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context={
        "cartItems": cartItems,
    }
    return render(request, 'resturant/home.html', context)

def menu(request):

    fries = MenuItem.objects.filter(item_type="fries")
    entrees = MenuItem.objects.filter(item_type="entree")
    aioliSauces = MenuItem.objects.filter(sauce_type="aioli")
    ketchupSauces = MenuItem.objects.filter(sauce_type="ketchup")
    context = {
        "fries": fries,
        "entrees" : entrees,
        "aioli_sauces" : aioliSauces,
        "ketchup_sauces" : ketchupSauces,
    }
    return render(request, 'resturant/menu.html', context)

def menu_details(request, pk):
    #add a try catch to get the 404 on an object not found
    menu_item_name = MenuItem.objects.get(id=pk)
    context = {
        "menu_item_name": menu_item_name,
    }
    return render(request, 'resturant/menu_item_details.html', context)

@unaunthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
        else:
            messages.info(request, "Username or Password is incorrect")

    context = {
    }
    return render(request, 'resturant/login.html', context)

@login_required(login_url='login')
def logoutPage(request):
    logout(request)
    return redirect('home')

@unaunthenticated_user
def registerPage(request):
    customerGroup = Group.objects.get(name="customer")

    form = CreateUserForm()
    errorList = []
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            """
            This was used before siganls
            newUser = User.objects.get(username=form.cleaned_data.get('username'))
            customerGroup.user_set.add(newUser)
            email = form.cleaned_data.get('email')

resturant/templates/resturant/admin_menu_item.html
{% extends 'resturant/main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<link href="{% static 'css/admin_menu_item.css' %}" rel="stylesheet">

<br>
<div class="row">
  <div class="col-md-3 ml-4 column">
    <div class="card card-body column-card">
      <a class="btn btn-warning" href="{% url 'home' %}"> &#8592; Back to Home</a>
      <hr>
      <h3 style="text-align: center">Menu Settings</h3>
      <hr>
      <h4>Current Items:</h4>
      <h6>Click on item for details</h6>
      {% for item in items %}
      <p><a href='{% url "admin_detail" item.id %}'>{{item}}</a></p>
      {% endfor %}
    </div>
  </div>
  <div class="col-md-3 column need-margin">
    <div class="card column-card card-body">
      <div class="card-title">
        <hr>
        <h3 style="text-align: center">Add Item</h3>
        <hr>
      </div>
      <div class="card-body">
        <form class="" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_name" class='h5'>Item Name</label>
            {% render_field form.name class="form-control" %}
          </div>

          <div class="form-group">
            <label for="id_description" class='h5'>Description</label>
            {% render_field form.description class="form-control" %}
          </div>

          <div class="form-group">
            <label for="id_price" class='h5'>Price</label>
            {% render_field form.price class="form-control" %}
          </div>

          <div class="form-group">
            <label for="id_item_type" class='h5'>Item Type</label>
            {% render_field form.item_type class="form-control" %}
          </div>

          <div class="form-group">
            <label for="id_item_type" class='h5'>Item Image</label>
            {% render_field form.item_pic class="form-control" %}
          </div>

          <div class="text-center">
            <button type="submit" name="submit" class='btn btn-primary'>Add Item</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="col-md-3 column">
    <div class="card column-card card-body need-margin need-further-margin">
      <div class="card-title" style="text-align: center">
        <hr>
        <h3>Current Orders</h3>
        <small class="text-muted">Click for details</small>
        <hr>
      </div>
      <div class="card-body">
        <h5 style="text-decoration: underline;">Confirmed Orders</h5>
        {% for order in confirmed_orders %}
        <p><a href="{% url 'order_details' order.id %}">{% render_field order %}</a></p>
        {% endfor %}
        <hr>
        <h5 style="text-decoration: underline;">Orders out for Delivery</h5>
        {% for order in orders_being_delivered %}
        <p><a href="{% url 'order_details' order.id %}">{% render_field order %}</a></p>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'js/admin_menu_item.js' %}"></script>

{% endblock %}

resturant/templates/resturant/checkout.html
{% extends "resturant/main.html" %}
{% load static %}
{% block content %}

<style media="screen">
  .checkout{
    margin: 1em;
  }
  .form-field{
    display: inline-block;
  }
</style>

<script type="text/javascript">
  const orderId = "{{order.id}}";
  var total = "{{order.get_cart_total}}";
  const homePage = "{% url 'home' %}";
</script>

<br>
<div class="row ml-2 mr-2">
  <div class="col-lg-6">
    <div class="box-element" id="form-wrapper">
      <form class="" action="" method="post" id="form">
        {% csrf_token %}
        <div class="" id="user-info">
          <p>Personal Info</p>
          <div class="mb-1">
            <input required class="form-control" type="text" name="name" value="" placeholder="Name..">
          </div>
          <div class="">
            <input required class="form-control" type="email" name="email" value="" placeholder="Email..">
          </div>
        </div>
        <div class="" id="shipping-info">
          <hr>
          <p>Delivery Options</p>
          <div class="form-field">
            <label for="pickup">Pickup</label>
            <input type="radio" name="pickup" id="pickup" value="pickup" onclick="isDeliveryClicked()">
            <label for="delivery">Delivery</label>
            <input type="radio" name="pickup" id="delivery" value="delivery" onclick="isDeliveryClicked()" checked>
            {{order.pickup}}
          </div>
          <hr>
          <div id='shipping-form'>
            <div class="form-field">
              <input class="form-control checkout" type="text" name="address" placeholder="Address..">
            </div>
            <div class="form-field">
              <input class="form-control checkout" type="text" name="city" placeholder="City..">
            </div>
            <div class="form-field">
              <input class="form-control checkout" type="text" name="state" placeholder="State..">
            </div>
            <div class="form-field">
              <input class="form-control checkout" type="text" name="zipcode" placeholder="Zip code..">
            </div>
          </div>
        </div>
        <hr>
        <input type="submit" value="Continue" id="form-button" class="btn btn-success btn-block">
      </form>
    </div>
    <br>

    <div class="box-element d-none" id="payment-info" style="text-align: center;">
      <small>Payment Options</small>
      <div id="paypal-button-container"></div>
    </div>
  </div>

  <div class="col-lg-6">
    <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
      <hr>
      <h3>Order Summary</h3>
      <hr>

      {% for item in items %}
      <div class="cart-row">
        <div style="flex:2"><img class="row-image" src="{{item.product.item_pic.url}}" alt="" style="height: 60px;"></div>
        <div style="flex:2">{{item.product.name}}</div>
        <div style="flex:1">{{item.product.price|floatformat:2}}</div>
        <div style="flex:1">{{item.quantity}}</div>
      </div>
      {% endfor %}

      <h5>Items: {{order.get_cart_items}}</h5>
      <h5>Total: {{order.get_cart_total}}</h5>
    </div>
  </div>
</div>
  <script type="text/javascript" src="{% static 'js/checkout.js' %}"></script>

  <script src="https://www.paypal.com/sdk/js?client-id=AXazEi_itvlBJdvT823mL_FNMov-QiwI_NY9B7dQeILeWGm_XYZjlBobYDlp995Q_bQDVzafZrILzAWc&enable-funding=venmo&currency=USD" data-sdk-integration-source="button-factory"></script>
  <script>
    paypal.Buttons({

      style: {
                color:  'blue',
                shape:  'pill',
                label:  'pay',
                height: 40,
                size: 'medium'
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];

                    submitFormData()
                    // Replace the above to show a success message within this page, e.g.
                    // const element = document.getElementById('paypal-button-container');
                    // element.innerHTML = '';
                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                    actions.redirect(homePage);
                });
            }


        }).render('#paypal-button-container');
  </script>

{% endblock %}

resturant/templates/resturant/delete_item.html
{% extends 'resturant/main.html' %}
{% load static %}

{% block content %}

<style media="screen">
  .shadow-box{
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
</style>
<br>
<div class="row">
  <div class="col col-md-9" style='margin: auto;'>
    <div class="card shadow-box">
      <div class="card-title">
        <h3 style="padding: 1em;">Are you sure you want to delete {{item}}?</h3>
      </div>
      <div class="card-body">
        <form class="" action="" method="post">
          {% csrf_token %}
          <a href="{% url 'admin_detail' item.id %}" class='btn btn-warning'>Cancel</a>

          <input type="submit" name="delete" value="Confirm" class='btn btn-danger'>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

resturant/templates/resturant/menu_item_details.html
{% extends 'resturant/main.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/menu_item_details.css' %}">

<div class="row">
  <div class="col">
    <a href="{% url 'menu' %}" class="btn btn-info" id="return-button">Back to Menu</a>
  </div>
</div>

<div class="container">

  <!-- Title -->
  <div class="row" id="title-div">
    <div class="col col-12">
      <h1 class="text-center">{{menu_item_name}}</h1>
    </div>
  </div>

  <!-- Pic -->
  <div class="row" id="title-div" style="text-align: center;">
    <div class="col col-12">
      <img src="{{menu_item_name.item_pic.url}}" id="menu-item-img">
    </div>
  </div>


  <div class="details">
    <!-- Description -->
    <div class="row desc-card">
      <div class="col col-12 card desc">
        <p class="text-center">{{menu_item_name.description}}</p>
        <!-- Price -->
        <p class="text-center">${{menu_item_name.price}}</p>
      </div>
    </div>

    <div class="row button-div" style="text-align: center;">
      <div class="col col-12">
        <button data-product={{menu_item_name.id}} data-action="add" type="button" name="button"
          class="btn btn-outline-secondary add-btn update-cart" style="margin: auto;">Add To Cart</button>
      </div>
    </div>

  </div>

  {% endblock %}

resturant/templates/resturant/menu_items_details_admin.html
{% extends 'resturant/main.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<style>
  #messages {
    background-color: grey;
    color: #fff;
    padding: 10px;
    margin-top: 10px;
  }

  #messages ul {
    list-style-type: none;
  }

  @media screen and (max-width: 1100px) {
    .menu-item-card {
      width: 80%;
      margin-top: 2em !important;
      margin: auto;
    }

    .delete-button-div {
      margin-top: 1em;
      text-align: center;
    }
  }
</style>

<br>
<div>
  <div class="container-fluid">
    <div class="row">
      <div class="col col-1">
        <a class=" btn btn-warning" id="return" href="{% url 'admin_menu_item' %}">Return</a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-5 menu-item" style="margin: auto;">
      <div class="card menu-item-card">
        <div class="card-title">
          <h2 class='text-center mt-2'>Item Changes</h2>
        </div>
        <div class="card-body">
          <form class="" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_name" class='h5'>Item Name</label>
              {% render_field form.name class="form-control" %}
            </div>

            <div class="form-group">
              <label for="id_description" class='h5'>Description</label>
              {% render_field form.description class="form-control" %}
            </div>

            <div class="form-group">
              <label for="id_price" class='h5'>Price</label>
              {% render_field form.price class="form-control" %}
            </div>

            <div class="form-group">
              <label for="id_item_type" class='h5'>Type</label>
              {% render_field form.item_type class="form-control" %}
            </div>

            {% if item.item_type == "sauce" %}
            <div class="form-group">
              <label for="id_sauce_type" class='h5'>Sauce Type</label>
              {% render_field form.sauce_type class="form-control" %}
            </div>
            {% endif %}

            <div class="form-group">
              <label for="id_item_pic" class='h5'>Image</label>
              {% render_field form.item_pic class="form-control" %}
            </div>

            <div class="text-center">
              <input type="submit" name="submit" value="Submit Changes" class='btn btn-primary'>
            </div>

          </form>

          <div class="form-group delete-button-div">
            <a href="{% url 'delete_item' item.id %}" class='btn btn-danger' id="delete-button">Delete</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'js/admin_menu_item_details.js' %}"></script>

{% endblock %}